run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
